// @flow
export default (): Array<string> => [
  'Open Source',
  'JavaScript',
  'React',
  'React Native',
  'Agile',
  'Relay',
  'GraphQL',
  'Flow',
  'Node',
  'Mountain Biking',
  'GreenSock',
  'MongoDB',
  'Groovy',
  'Material Design',
  'Bootstrap',
  'Snowboarding',
  'Material UI',
  'WebStorm',
  'Digital Ocean',
  'Webpack',
  'Extreme Programming',
  'React Storybook',
  'Colorado',
];
