// flow-typed signature: a2c3656a933601ecf856d87441446717
// flow-typed version: <<STUB>>/graphql-playground-middleware-express_v^1.5.6/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-playground-middleware-express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-playground-middleware-express' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-playground-middleware-express/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-playground-middleware-express/dist/index.js' {
  declare module.exports: $Exports<'graphql-playground-middleware-express/dist/index'>;
}
