// flow-typed signature: 7184c21f90a18b97f721127dd5fead33
// flow-typed version: <<STUB>>/sparkpost_v^2.1.2/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sparkpost'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sparkpost' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sparkpost/ajh_test' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/baseObject/getDomainsList' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/inboundDomains/create' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/inboundDomains/delete' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/inboundDomains/get' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/inboundDomains/list' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/messageEvents/search_campaignClicks' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/messageEvents/search_default' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/messageEvents/search_messageEvents' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/recipientLists/create' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/recipientLists/delete' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/recipientLists/get' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/recipientLists/list' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/recipientLists/update' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/relayWebhooks/create' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/relayWebhooks/delete' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/relayWebhooks/get' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/relayWebhooks/list' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/relayWebhooks/update' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/sendingDomains/create' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/sendingDomains/delete' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/sendingDomains/get' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/sendingDomains/list' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/sendingDomains/update' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/sendingDomains/verify' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/subaccounts/create' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/subaccounts/get' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/subaccounts/list' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/subaccounts/update' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/suppressionList/delete' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/suppressionList/get' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/suppressionList/list' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/suppressionList/upsert_bulk' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/suppressionList/upsert' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/templates/create' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/templates/delete' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/templates/get_draft' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/templates/get' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/templates/list' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/templates/preview' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/templates/update_published' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/templates/update' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/transmissions/get' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/transmissions/list_by_campaign' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/transmissions/list_by_template' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/transmissions/list' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/transmissions/send_all_fields' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/transmissions/send_mime_parts' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/transmissions/send_rfc822' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/transmissions/send_stored_recipients_inline_content' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/transmissions/send_stored_recipients_stored_content' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/transmissions/send_stored_template' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/transmissions/send_with_bcc_sugar' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/transmissions/send_with_bcc' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/transmissions/send_with_cc_sugar' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/transmissions/send_with_cc' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/webhooks/create' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/webhooks/delete' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/webhooks/get' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/webhooks/getBatchStatus' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/webhooks/getDocumentation' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/webhooks/getSamples' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/webhooks/list' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/webhooks/update' {
  declare module.exports: any;
}

declare module 'sparkpost/examples/webhooks/validate' {
  declare module.exports: any;
}

declare module 'sparkpost/lib/inboundDomains' {
  declare module.exports: any;
}

declare module 'sparkpost/lib/messageEvents' {
  declare module.exports: any;
}

declare module 'sparkpost/lib/recipientLists' {
  declare module.exports: any;
}

declare module 'sparkpost/lib/relayWebhooks' {
  declare module.exports: any;
}

declare module 'sparkpost/lib/sendingDomains' {
  declare module.exports: any;
}

declare module 'sparkpost/lib/sparkpost' {
  declare module.exports: any;
}

declare module 'sparkpost/lib/subaccounts' {
  declare module.exports: any;
}

declare module 'sparkpost/lib/suppressionList' {
  declare module.exports: any;
}

declare module 'sparkpost/lib/templates' {
  declare module.exports: any;
}

declare module 'sparkpost/lib/transmissions' {
  declare module.exports: any;
}

declare module 'sparkpost/lib/webhooks' {
  declare module.exports: any;
}

declare module 'sparkpost/lib/withCallback' {
  declare module.exports: any;
}

declare module 'sparkpost/test/spec/inboundDomains.spec' {
  declare module.exports: any;
}

declare module 'sparkpost/test/spec/messageEvents.spec' {
  declare module.exports: any;
}

declare module 'sparkpost/test/spec/recipientLists.spec' {
  declare module.exports: any;
}

declare module 'sparkpost/test/spec/relayWebhooks.spec' {
  declare module.exports: any;
}

declare module 'sparkpost/test/spec/sendingDomains.spec' {
  declare module.exports: any;
}

declare module 'sparkpost/test/spec/sparkpost.spec' {
  declare module.exports: any;
}

declare module 'sparkpost/test/spec/subaccounts.spec' {
  declare module.exports: any;
}

declare module 'sparkpost/test/spec/suppressionList.spec' {
  declare module.exports: any;
}

declare module 'sparkpost/test/spec/templates.spec' {
  declare module.exports: any;
}

declare module 'sparkpost/test/spec/transmissions.spec' {
  declare module.exports: any;
}

declare module 'sparkpost/test/spec/webhooks.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sparkpost/ajh_test.js' {
  declare module.exports: $Exports<'sparkpost/ajh_test'>;
}
declare module 'sparkpost/examples/baseObject/getDomainsList.js' {
  declare module.exports: $Exports<'sparkpost/examples/baseObject/getDomainsList'>;
}
declare module 'sparkpost/examples/inboundDomains/create.js' {
  declare module.exports: $Exports<'sparkpost/examples/inboundDomains/create'>;
}
declare module 'sparkpost/examples/inboundDomains/delete.js' {
  declare module.exports: $Exports<'sparkpost/examples/inboundDomains/delete'>;
}
declare module 'sparkpost/examples/inboundDomains/get.js' {
  declare module.exports: $Exports<'sparkpost/examples/inboundDomains/get'>;
}
declare module 'sparkpost/examples/inboundDomains/list.js' {
  declare module.exports: $Exports<'sparkpost/examples/inboundDomains/list'>;
}
declare module 'sparkpost/examples/messageEvents/search_campaignClicks.js' {
  declare module.exports: $Exports<'sparkpost/examples/messageEvents/search_campaignClicks'>;
}
declare module 'sparkpost/examples/messageEvents/search_default.js' {
  declare module.exports: $Exports<'sparkpost/examples/messageEvents/search_default'>;
}
declare module 'sparkpost/examples/messageEvents/search_messageEvents.js' {
  declare module.exports: $Exports<'sparkpost/examples/messageEvents/search_messageEvents'>;
}
declare module 'sparkpost/examples/recipientLists/create.js' {
  declare module.exports: $Exports<'sparkpost/examples/recipientLists/create'>;
}
declare module 'sparkpost/examples/recipientLists/delete.js' {
  declare module.exports: $Exports<'sparkpost/examples/recipientLists/delete'>;
}
declare module 'sparkpost/examples/recipientLists/get.js' {
  declare module.exports: $Exports<'sparkpost/examples/recipientLists/get'>;
}
declare module 'sparkpost/examples/recipientLists/list.js' {
  declare module.exports: $Exports<'sparkpost/examples/recipientLists/list'>;
}
declare module 'sparkpost/examples/recipientLists/update.js' {
  declare module.exports: $Exports<'sparkpost/examples/recipientLists/update'>;
}
declare module 'sparkpost/examples/relayWebhooks/create.js' {
  declare module.exports: $Exports<'sparkpost/examples/relayWebhooks/create'>;
}
declare module 'sparkpost/examples/relayWebhooks/delete.js' {
  declare module.exports: $Exports<'sparkpost/examples/relayWebhooks/delete'>;
}
declare module 'sparkpost/examples/relayWebhooks/get.js' {
  declare module.exports: $Exports<'sparkpost/examples/relayWebhooks/get'>;
}
declare module 'sparkpost/examples/relayWebhooks/list.js' {
  declare module.exports: $Exports<'sparkpost/examples/relayWebhooks/list'>;
}
declare module 'sparkpost/examples/relayWebhooks/update.js' {
  declare module.exports: $Exports<'sparkpost/examples/relayWebhooks/update'>;
}
declare module 'sparkpost/examples/sendingDomains/create.js' {
  declare module.exports: $Exports<'sparkpost/examples/sendingDomains/create'>;
}
declare module 'sparkpost/examples/sendingDomains/delete.js' {
  declare module.exports: $Exports<'sparkpost/examples/sendingDomains/delete'>;
}
declare module 'sparkpost/examples/sendingDomains/get.js' {
  declare module.exports: $Exports<'sparkpost/examples/sendingDomains/get'>;
}
declare module 'sparkpost/examples/sendingDomains/list.js' {
  declare module.exports: $Exports<'sparkpost/examples/sendingDomains/list'>;
}
declare module 'sparkpost/examples/sendingDomains/update.js' {
  declare module.exports: $Exports<'sparkpost/examples/sendingDomains/update'>;
}
declare module 'sparkpost/examples/sendingDomains/verify.js' {
  declare module.exports: $Exports<'sparkpost/examples/sendingDomains/verify'>;
}
declare module 'sparkpost/examples/subaccounts/create.js' {
  declare module.exports: $Exports<'sparkpost/examples/subaccounts/create'>;
}
declare module 'sparkpost/examples/subaccounts/get.js' {
  declare module.exports: $Exports<'sparkpost/examples/subaccounts/get'>;
}
declare module 'sparkpost/examples/subaccounts/list.js' {
  declare module.exports: $Exports<'sparkpost/examples/subaccounts/list'>;
}
declare module 'sparkpost/examples/subaccounts/update.js' {
  declare module.exports: $Exports<'sparkpost/examples/subaccounts/update'>;
}
declare module 'sparkpost/examples/suppressionList/delete.js' {
  declare module.exports: $Exports<'sparkpost/examples/suppressionList/delete'>;
}
declare module 'sparkpost/examples/suppressionList/get.js' {
  declare module.exports: $Exports<'sparkpost/examples/suppressionList/get'>;
}
declare module 'sparkpost/examples/suppressionList/list.js' {
  declare module.exports: $Exports<'sparkpost/examples/suppressionList/list'>;
}
declare module 'sparkpost/examples/suppressionList/upsert_bulk.js' {
  declare module.exports: $Exports<'sparkpost/examples/suppressionList/upsert_bulk'>;
}
declare module 'sparkpost/examples/suppressionList/upsert.js' {
  declare module.exports: $Exports<'sparkpost/examples/suppressionList/upsert'>;
}
declare module 'sparkpost/examples/templates/create.js' {
  declare module.exports: $Exports<'sparkpost/examples/templates/create'>;
}
declare module 'sparkpost/examples/templates/delete.js' {
  declare module.exports: $Exports<'sparkpost/examples/templates/delete'>;
}
declare module 'sparkpost/examples/templates/get_draft.js' {
  declare module.exports: $Exports<'sparkpost/examples/templates/get_draft'>;
}
declare module 'sparkpost/examples/templates/get.js' {
  declare module.exports: $Exports<'sparkpost/examples/templates/get'>;
}
declare module 'sparkpost/examples/templates/list.js' {
  declare module.exports: $Exports<'sparkpost/examples/templates/list'>;
}
declare module 'sparkpost/examples/templates/preview.js' {
  declare module.exports: $Exports<'sparkpost/examples/templates/preview'>;
}
declare module 'sparkpost/examples/templates/update_published.js' {
  declare module.exports: $Exports<'sparkpost/examples/templates/update_published'>;
}
declare module 'sparkpost/examples/templates/update.js' {
  declare module.exports: $Exports<'sparkpost/examples/templates/update'>;
}
declare module 'sparkpost/examples/transmissions/get.js' {
  declare module.exports: $Exports<'sparkpost/examples/transmissions/get'>;
}
declare module 'sparkpost/examples/transmissions/list_by_campaign.js' {
  declare module.exports: $Exports<'sparkpost/examples/transmissions/list_by_campaign'>;
}
declare module 'sparkpost/examples/transmissions/list_by_template.js' {
  declare module.exports: $Exports<'sparkpost/examples/transmissions/list_by_template'>;
}
declare module 'sparkpost/examples/transmissions/list.js' {
  declare module.exports: $Exports<'sparkpost/examples/transmissions/list'>;
}
declare module 'sparkpost/examples/transmissions/send_all_fields.js' {
  declare module.exports: $Exports<'sparkpost/examples/transmissions/send_all_fields'>;
}
declare module 'sparkpost/examples/transmissions/send_mime_parts.js' {
  declare module.exports: $Exports<'sparkpost/examples/transmissions/send_mime_parts'>;
}
declare module 'sparkpost/examples/transmissions/send_rfc822.js' {
  declare module.exports: $Exports<'sparkpost/examples/transmissions/send_rfc822'>;
}
declare module 'sparkpost/examples/transmissions/send_stored_recipients_inline_content.js' {
  declare module.exports: $Exports<'sparkpost/examples/transmissions/send_stored_recipients_inline_content'>;
}
declare module 'sparkpost/examples/transmissions/send_stored_recipients_stored_content.js' {
  declare module.exports: $Exports<'sparkpost/examples/transmissions/send_stored_recipients_stored_content'>;
}
declare module 'sparkpost/examples/transmissions/send_stored_template.js' {
  declare module.exports: $Exports<'sparkpost/examples/transmissions/send_stored_template'>;
}
declare module 'sparkpost/examples/transmissions/send_with_bcc_sugar.js' {
  declare module.exports: $Exports<'sparkpost/examples/transmissions/send_with_bcc_sugar'>;
}
declare module 'sparkpost/examples/transmissions/send_with_bcc.js' {
  declare module.exports: $Exports<'sparkpost/examples/transmissions/send_with_bcc'>;
}
declare module 'sparkpost/examples/transmissions/send_with_cc_sugar.js' {
  declare module.exports: $Exports<'sparkpost/examples/transmissions/send_with_cc_sugar'>;
}
declare module 'sparkpost/examples/transmissions/send_with_cc.js' {
  declare module.exports: $Exports<'sparkpost/examples/transmissions/send_with_cc'>;
}
declare module 'sparkpost/examples/webhooks/create.js' {
  declare module.exports: $Exports<'sparkpost/examples/webhooks/create'>;
}
declare module 'sparkpost/examples/webhooks/delete.js' {
  declare module.exports: $Exports<'sparkpost/examples/webhooks/delete'>;
}
declare module 'sparkpost/examples/webhooks/get.js' {
  declare module.exports: $Exports<'sparkpost/examples/webhooks/get'>;
}
declare module 'sparkpost/examples/webhooks/getBatchStatus.js' {
  declare module.exports: $Exports<'sparkpost/examples/webhooks/getBatchStatus'>;
}
declare module 'sparkpost/examples/webhooks/getDocumentation.js' {
  declare module.exports: $Exports<'sparkpost/examples/webhooks/getDocumentation'>;
}
declare module 'sparkpost/examples/webhooks/getSamples.js' {
  declare module.exports: $Exports<'sparkpost/examples/webhooks/getSamples'>;
}
declare module 'sparkpost/examples/webhooks/list.js' {
  declare module.exports: $Exports<'sparkpost/examples/webhooks/list'>;
}
declare module 'sparkpost/examples/webhooks/update.js' {
  declare module.exports: $Exports<'sparkpost/examples/webhooks/update'>;
}
declare module 'sparkpost/examples/webhooks/validate.js' {
  declare module.exports: $Exports<'sparkpost/examples/webhooks/validate'>;
}
declare module 'sparkpost/lib/inboundDomains.js' {
  declare module.exports: $Exports<'sparkpost/lib/inboundDomains'>;
}
declare module 'sparkpost/lib/messageEvents.js' {
  declare module.exports: $Exports<'sparkpost/lib/messageEvents'>;
}
declare module 'sparkpost/lib/recipientLists.js' {
  declare module.exports: $Exports<'sparkpost/lib/recipientLists'>;
}
declare module 'sparkpost/lib/relayWebhooks.js' {
  declare module.exports: $Exports<'sparkpost/lib/relayWebhooks'>;
}
declare module 'sparkpost/lib/sendingDomains.js' {
  declare module.exports: $Exports<'sparkpost/lib/sendingDomains'>;
}
declare module 'sparkpost/lib/sparkpost.js' {
  declare module.exports: $Exports<'sparkpost/lib/sparkpost'>;
}
declare module 'sparkpost/lib/subaccounts.js' {
  declare module.exports: $Exports<'sparkpost/lib/subaccounts'>;
}
declare module 'sparkpost/lib/suppressionList.js' {
  declare module.exports: $Exports<'sparkpost/lib/suppressionList'>;
}
declare module 'sparkpost/lib/templates.js' {
  declare module.exports: $Exports<'sparkpost/lib/templates'>;
}
declare module 'sparkpost/lib/transmissions.js' {
  declare module.exports: $Exports<'sparkpost/lib/transmissions'>;
}
declare module 'sparkpost/lib/webhooks.js' {
  declare module.exports: $Exports<'sparkpost/lib/webhooks'>;
}
declare module 'sparkpost/lib/withCallback.js' {
  declare module.exports: $Exports<'sparkpost/lib/withCallback'>;
}
declare module 'sparkpost/test/spec/inboundDomains.spec.js' {
  declare module.exports: $Exports<'sparkpost/test/spec/inboundDomains.spec'>;
}
declare module 'sparkpost/test/spec/messageEvents.spec.js' {
  declare module.exports: $Exports<'sparkpost/test/spec/messageEvents.spec'>;
}
declare module 'sparkpost/test/spec/recipientLists.spec.js' {
  declare module.exports: $Exports<'sparkpost/test/spec/recipientLists.spec'>;
}
declare module 'sparkpost/test/spec/relayWebhooks.spec.js' {
  declare module.exports: $Exports<'sparkpost/test/spec/relayWebhooks.spec'>;
}
declare module 'sparkpost/test/spec/sendingDomains.spec.js' {
  declare module.exports: $Exports<'sparkpost/test/spec/sendingDomains.spec'>;
}
declare module 'sparkpost/test/spec/sparkpost.spec.js' {
  declare module.exports: $Exports<'sparkpost/test/spec/sparkpost.spec'>;
}
declare module 'sparkpost/test/spec/subaccounts.spec.js' {
  declare module.exports: $Exports<'sparkpost/test/spec/subaccounts.spec'>;
}
declare module 'sparkpost/test/spec/suppressionList.spec.js' {
  declare module.exports: $Exports<'sparkpost/test/spec/suppressionList.spec'>;
}
declare module 'sparkpost/test/spec/templates.spec.js' {
  declare module.exports: $Exports<'sparkpost/test/spec/templates.spec'>;
}
declare module 'sparkpost/test/spec/transmissions.spec.js' {
  declare module.exports: $Exports<'sparkpost/test/spec/transmissions.spec'>;
}
declare module 'sparkpost/test/spec/webhooks.spec.js' {
  declare module.exports: $Exports<'sparkpost/test/spec/webhooks.spec'>;
}
