// flow-typed signature: 35f0141f02a43faef0fe43b72bb3d33f
// flow-typed version: <<STUB>>/webpack-externals-plugin_v^1.0.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-externals-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-externals-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webpack-externals-plugin/index' {
  declare module.exports: $Exports<'webpack-externals-plugin'>;
}
declare module 'webpack-externals-plugin/index.js' {
  declare module.exports: $Exports<'webpack-externals-plugin'>;
}
