// flow-typed signature: 6dd0aa37a2c72feaf22905b3e3c0b786
// flow-typed version: <<STUB>>/jest-css-modules_v^1.1.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-css-modules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-css-modules' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'jest-css-modules/index' {
  declare module.exports: $Exports<'jest-css-modules'>;
}
declare module 'jest-css-modules/index.js' {
  declare module.exports: $Exports<'jest-css-modules'>;
}
